import type { Category, UnitDefinition } from './types';
const linear=(category:Category,id:string,name:string,symbol:string,aliases:string[],factor:number,formula?:string):UnitDefinition=>({id,name,symbol,aliases:[id,symbol,...aliases].map(x=>x.toLowerCase()),category,toBase:v=>v*factor,fromBase:v=>v/factor,formula});
const affine=(category:Category,id:string,name:string,symbol:string,aliases:string[],toBase:(v:number)=>number,fromBase:(v:number)=>number,formula:string):UnitDefinition=>({id,name,symbol,aliases:[id,symbol,...aliases].map(x=>x.toLowerCase()),category,toBase,fromBase,formula});
export const UNITS: UnitDefinition[] = [
linear('length','millimeter','Millimeter','mm',['millimeters'],0.001),linear('length','centimeter','Centimeter','cm',['centimeters'],0.01),linear('length','meter','Meter','m',['meters'],1),linear('length','kilometer','Kilometer','km',['kilometers','kilometre','kilometres'],1000),linear('length','inch','Inch','in',['inches'],0.0254),linear('length','foot','Foot','ft',['feet'],0.3048),linear('length','yard','Yard','yd',['yards'],0.9144),linear('length','mile','Mile','mi',['miles'],1609.344),linear('length','nautical-mile','Nautical mile','nmi',['nautical miles'],1852),linear('length','light-year','Light-year','ly',['light years'],9.460730472e15),
linear('mass','milligram','Milligram','mg',['milligrams'],0.000001),linear('mass','gram','Gram','g',['grams'],0.001),linear('mass','kilogram','Kilogram','kg',['kilograms','kilo'],1),linear('mass','metric-ton','Metric ton','t',['tonne','tonnes'],1000),linear('mass','ounce','Ounce','oz',['ounces'],0.028349523125),linear('mass','pound','Pound','lb',['lbs','pounds'],0.45359237),linear('mass','stone','Stone','st',['stones'],6.35029318),
affine('temperature','celsius','Celsius','°C',['c','celcius'],v=>v,v=>v,'°C'),affine('temperature','fahrenheit','Fahrenheit','°F',['f'],v=>(v-32)*5/9,v=>v*9/5+32,'°F = (°C × 9/5) + 32'),affine('temperature','kelvin','Kelvin','K',['k'],v=>v-273.15,v=>v+273.15,'K = °C + 273.15'),
linear('area','square-millimeter','Square millimeter','mm²',['mm2'],1e-6),linear('area','square-centimeter','Square centimeter','cm²',['cm2'],1e-4),linear('area','square-meter','Square meter','m²',['m2'],1),linear('area','square-kilometer','Square kilometer','km²',['km2'],1e6),linear('area','square-inch','Square inch','in²',['in2'],0.00064516),linear('area','square-foot','Square foot','ft²',['ft2','sq ft','sqft','square feet'],0.09290304),linear('area','square-yard','Square yard','yd²',['yd2','sq yd'],0.83612736),linear('area','acre','Acre','ac',['acres'],4046.8564224),linear('area','hectare','Hectare','ha',['hectares'],10000),
linear('volume','milliliter','Milliliter','mL',['ml','milliliters'],0.001),linear('volume','liter','Liter','L',['l','liters','litres'],0.001),linear('volume','cubic-meter','Cubic meter','m³',['m3'],1),linear('volume','cubic-foot','Cubic foot','ft³',['ft3'],0.028316846592),linear('volume','cubic-inch','Cubic inch','in³',['in3'],0.000016387064),linear('volume','us-gallon','US gallon','US gal',['gallon','gallons','us gallons'],0.003785411784),linear('volume','imperial-gallon','Imperial gallon','Imp gal',['imperial gallons'],0.00454609),linear('volume','quart','Quart','qt',['quarts'],0.000946352946),linear('volume','pint','Pint','pt',['pints'],0.000473176473),linear('volume','cup','Cup','cup',['cups'],0.0002365882365),
linear('speed','meter-per-second','Meter per second','m/s',['mps'],1),linear('speed','kilometer-per-hour','Kilometer per hour','km/h',['kph','kmh'],1/3.6),linear('speed','mile-per-hour','Mile per hour','mph',['mi/h'],0.44704),linear('speed','knot','Knot','kn',['knots'],0.514444444444),linear('speed','foot-per-second','Foot per second','ft/s',['fps'],0.3048),
linear('time','millisecond','Millisecond','ms',['milliseconds'],0.001),linear('time','second','Second','s',['sec','seconds'],1),linear('time','minute','Minute','min',['minutes'],60),linear('time','hour','Hour','h',['hr','hours'],3600),linear('time','day','Day','d',['days'],86400),linear('time','week','Week','wk',['weeks'],604800),linear('time','month','Month','mo',['months'],2629800),linear('time','year','Year','yr',['years'],31557600),
linear('energy','joule','Joule','J',['joules'],1),linear('energy','kilojoule','Kilojoule','kJ',['kilojoules'],1000),linear('energy','calorie','Calorie','cal',['calories'],4.184),linear('energy','kilocalorie','Kilocalorie','kcal',['kilocalories'],4184),linear('energy','watt-hour','Watt-hour','Wh',['watt hours'],3600),linear('energy','kilowatt-hour','Kilowatt-hour','kWh',['kilowatt hours'],3.6e6),linear('energy','btu','BTU','BTU',['btu'],1055.05585262),
linear('power','watt','Watt','W',['watts'],1),linear('power','kilowatt','Kilowatt','kW',['kilowatts'],1000),linear('power','megawatt','Megawatt','MW',['megawatts'],1e6),linear('power','horsepower','Horsepower','hp',['horsepower'],745.699871582),
linear('pressure','pascal','Pascal','Pa',['pascals'],1),linear('pressure','kilopascal','Kilopascal','kPa',['kilopascals'],1000),linear('pressure','bar','Bar','bar',['bars'],100000),linear('pressure','psi','PSI','psi',['pounds per square inch'],6894.757293168),linear('pressure','atmosphere','Atmosphere','atm',['atmospheres'],101325),linear('pressure','mmhg','Millimeters of mercury','mmHg',['mm hg'],133.322387415),
linear('force','newton','Newton','N',['newtons'],1),linear('force','kilonewton','Kilonewton','kN',['kilonewtons'],1000),linear('force','pound-force','Pound-force','lbf',['pound force'],4.4482216152605),linear('force','kilogram-force','Kilogram-force','kgf',['kilogram force'],9.80665),
linear('torque','newton-meter','Newton-meter','N·m',['nm','newton meters'],1),linear('torque','pound-foot','Pound-foot','lb·ft',['lb-ft','pound feet'],1.3558179483314),linear('torque','pound-inch','Pound-inch','lb·in',['lb-in','pound inches'],0.1129848290276),
linear('frequency','hz','Hertz','Hz',['hertz'],1),linear('frequency','khz','Kilohertz','kHz',['kilohertz'],1000),linear('frequency','mhz','Megahertz','MHz',['megahertz'],1e6),linear('frequency','ghz','Gigahertz','GHz',['gigahertz'],1e9),
linear('density','kg-m3','Kilogram per cubic meter','kg/m³',['kg/m3'],1),linear('density','g-cm3','Gram per cubic centimeter','g/cm³',['g/cm3'],1000),linear('density','lb-ft3','Pound per cubic foot','lb/ft³',['lb/ft3'],16.01846337),
linear('digital','bit','Bit','bit',['bits','b'],1),linear('digital','byte','Byte','B',['bytes'],8),linear('digital','kilobyte','Kilobyte','KB',['kb','kilobytes'],8000),linear('digital','megabyte','Megabyte','MB',['mb','megabytes'],8e6),linear('digital','gigabyte','Gigabyte','GB',['gb','gigabytes'],8e9),linear('digital','terabyte','Terabyte','TB',['tb','terabytes'],8e12),linear('digital','petabyte','Petabyte','PB',['pb','petabytes'],8e15),linear('digital','kibibyte','Kibibyte','KiB',['kib'],8192),linear('digital','mebibyte','Mebibyte','MiB',['mib'],8388608),linear('digital','gibibyte','Gibibyte','GiB',['gib'],8589934592),linear('digital','tebibyte','Tebibyte','TiB',['tib'],8796093022208),
linear('data-transfer','bps','Bits per second','bps',['bit/s'],1),linear('data-transfer','kbps','Kilobits per second','Kbps',['kb/s'],1000),linear('data-transfer','mbps','Megabits per second','Mbps',['mb/s'],1e6),linear('data-transfer','gbps','Gigabits per second','Gbps',['gb/s'],1e9),linear('data-transfer','kbs','Kilobytes per second','KB/s',['kbps-bytes','KB/s','kb/s','kilobytes per second'],8000),linear('data-transfer','mbs','Megabytes per second','MB/s',['mbps-bytes','MB/s','mb/s','megabytes per second'],8e6),linear('data-transfer','gbs','Gigabytes per second','GB/s',['gbps-bytes','GB/s','gb/s','gigabytes per second'],8e9),
linear('pakistan-land','square-foot-pk','Square foot','ft²',['sq ft'],1),linear('pakistan-land','square-yard-pk','Square yard','yd²',['sq yd'],9),linear('pakistan-land','square-meter-pk','Square meter','m²',['sq m'],10.7639104167),linear('pakistan-land','acre-pk','Acre','acre',['acres'],43560),linear('pakistan-land','marla-standard','Marla (standard)','marla',['marla'],272.25),linear('pakistan-land','kanal-standard','Kanal (standard)','kanal',['kanal'],5445),
linear('pakistan-weight','gram-pk','Gram','g',['grams'],1),linear('pakistan-weight','kilogram-pk','Kilogram','kg',['kilograms'],1000),linear('pakistan-weight','tola','Tola','tola',['tolas'],11.6638125),linear('pakistan-weight','seer','Seer','seer',['seers'],933.10)
];
export const UNIT_MAP = new Map(UNITS.flatMap(u=>u.aliases.map(a=>[a,u] as const)));
