'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeftRight,Copy,Heart,History,Menu,Moon,Search,Sun,Zap,Trash2,Calculator,RefreshCw} from 'lucide-react';
import {ALL_UNITS,UNITS} from '@/lib/converter/definitions';
import {allConversions,convert,resolveUnit} from '@/lib/converter/engine';
import {parseConversionRequest} from '@/lib/parser/natural';

type Saved={id:string;input:string;result:string;category:string;createdAt:string;from:string;to:string};
const cats=[...new Set(UNITS.map(x=>x.category))];
const names:Record<string,string>={length:'Length',mass:'Mass',temperature:'Temperature',area:'Area',volume:'Volume',speed:'Speed',time:'Time',energy:'Energy',power:'Power',pressure:'Pressure',force:'Force',torque:'Torque',frequency:'Frequency',density:'Density',digital:'Digital Storage','data-transfer':'Data Transfer','pakistan-land':'Pakistan Land','pakistan-weight':'Pakistan Weight'};
const read=(k:string):Saved[]=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
const write=(k:string,v:Saved[])=>localStorage.setItem(k,JSON.stringify(v));
export default function Home(){
 const [cat,setCat]=useState('length'),[from,setFrom]=useState('kilometer'),[to,setTo]=useState('mile'),[value,setValue]=useState('1'),[smart,setSmart]=useState('5 kg to pounds'),[msg,setMsg]=useState(''),[dark,setDark]=useState(false),[history,setHistory]=useState<Saved[]>([]),[favorites,setFavorites]=useState<Saved[]>([]),[currency,setCurrency]=useState({amount:'1',from:'USD',to:'PKR',result:'',updated:''}),[calc,setCalc]=useState({kg:'70',m:'1.75'});
 useEffect(()=>{setHistory(read('zeta-history'));setFavorites(read('zeta-favorites'));const d=localStorage.getItem('zeta-theme')==='dark';setDark(d);document.documentElement.classList.toggle('dark',d);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
 const units=useMemo(()=>UNITS.filter(x=>x.category===cat),[cat]);
 const result=useMemo(()=>{try{return convert(Number(value),from,to).value}catch{return null}},[value,from,to]);
 const source=useMemo(()=>{try{return resolveUnit(from)}catch{return null}},[from]);
 const rows=useMemo(()=>{try{return allConversions(Number(value)||0,from)}catch{return[]}},[value,from]);
 const runSmart=()=>{const p=parseConversionRequest(smart);if(!p){setMsg('Request not recognized. Try “5 kg to pounds”, “37 C to F”, or “200 Mbps to MB/s”.');return}setCat(p.category);setFrom(p.from);setTo(p.to);setValue(String(p.value));setMsg('Smart conversion detected.');};
 const swap=()=>{setFrom(to);setTo(from)};
 const save=(fav=false)=>{if(result===null)return;const s=resolveUnit(from),t=resolveUnit(to);const item={id:crypto.randomUUID(),input:`${value} ${s.symbol}`,result:String(result),category:cat,createdAt:new Date().toISOString(),from:s.symbol,to:t.symbol};const key=fav?'zeta-favorites':'zeta-history';const arr=[item,...read(key).filter(x=>x.id!==item.id)].slice(0,fav?50:100);write(key,arr);fav?setFavorites(arr):setHistory(arr);setMsg(fav?'Added to favorites.':'Saved to history.');};
 const copy=(text:string)=>navigator.clipboard?.writeText(text).then(()=>setMsg('Copied.'));
 async function getCurrency(){setCurrency(c=>({...c,result:'Loading…'}));try{const r=await fetch(`/api/currency?base=${currency.from}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Live rates unavailable');const rate=d.rates[currency.to];if(typeof rate!=='number')throw new Error('Target currency is unavailable');setCurrency(c=>({...c,result:String(Number(c.amount)*rate),updated:d.updatedAt}));}catch(e){setCurrency(c=>({...c,result:e instanceof Error?e.message:'Live rates unavailable',updated:''}))}}
 const bmi=Number(calc.kg)/(Number(calc.m)**2);
 return <div className="app"><header className="top"><div className="container nav"><div className="brand"><span className="mark"><Zap size={18}/></span>ZETA</div><nav className="navlinks"><a href="#converter">Converter</a><a href="#currency">Currency</a><a href="#calculators">Calculators</a><a href="#history">History</a><a href="#favorites">Favorites</a></nav><div className="actions"><button className="iconbtn" aria-label="Theme" onClick={()=>{const n=!dark;setDark(n);localStorage.setItem('zeta-theme',n?'dark':'light');document.documentElement.classList.toggle('dark',n)}}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="iconbtn" aria-label="Menu"><Menu size={18}/></button></div></div></header>
 <main><section className="hero container"><div className="eyebrow">ZETA UNIVERSAL CONVERTER</div><h1>Convert Anything.<br/>Instantly.</h1><p className="lead">A premium universal conversion platform for science, engineering, digital, currency and Pakistan-specific units — with deterministic calculations and no fake rates.</p><div className="smart"><Search size={19} style={{margin:'13px 5px 0 10px',color:'var(--muted)'}}/><input value={smart} onChange={e=>setSmart(e.target.value)} onKeyDown={e=>e.key==='Enter'&&runSmart()} placeholder="Try: 5 kg to pounds" aria-label="Natural language conversion"/><button className="btn primary" onClick={runSmart}>Convert</button></div>{msg&&<div className="muted" style={{marginTop:10,fontSize:13}} role="status">{msg}</div>}</section>
 <section id="converter" className="section container"><div className="tabs">{cats.map(c=><button key={c} className={'tab '+(c===cat?'active':'')} onClick={()=>{setCat(c);const u=UNITS.filter(x=>x.category===c);setFrom(u[0].id);setTo(u[1]?.id||u[0].id)}}>{names[c]}</button>)}</div><div className="card"><div className="grid converter"><div><span className="label">Amount</span><input className="input" inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)}/><span className="label" style={{marginTop:15}}>From</span><select className="select" value={from} onChange={e=>setFrom(e.target.value)}>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.symbol})</option>)}</select></div><button className="iconbtn swap" aria-label="Swap" onClick={swap}><ArrowLeftRight size={19}/></button><div><span className="label">Converted result</span><div className="result">{result===null?'—':Number(result).toLocaleString(undefined,{maximumFractionDigits:10})}</div><span className="label" style={{marginTop:15}}>To</span><select className="select" value={to} onChange={e=>setTo(e.target.value)}>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.symbol})</option>)}</select></div></div>{result!==null&&source&&<div className="formula"><b>Formula</b><div style={{marginTop:5}}>{source.symbol} → {resolveUnit(to).symbol}: {Number(value)} × {(result/Number(value)).toPrecision(8)} = {result}</div></div>}<div className="tools"><button className="btn" onClick={()=>copy(String(result??''))}><Copy size={15} style={{verticalAlign:'-2px'}}/> Copy</button><button className="btn" onClick={()=>save(true)}><Heart size={15} style={{verticalAlign:'-2px'}}/> Favorite</button><button className="btn" onClick={()=>save()}><History size={15} style={{verticalAlign:'-2px'}}/> Save history</button></div></div></section>
 <section className="section container"><div className="card"><h2>All units</h2><p className="muted">Convert {value||0} {source?.symbol||''} into every unit in {names[cat]}.</p><div className="allgrid">{rows.map(r=><div className="unitrow" key={r.unit.id}><div><div className="unitvalue">{Number(r.value).toLocaleString(undefined,{maximumFractionDigits:10})}</div><div className="unitname">{r.unit.name} · {r.unit.symbol}</div></div><button className="iconbtn" onClick={()=>copy(String(r.value))} aria-label="Copy"><Copy size={15}/></button></div>)}</div></div></section>
 <section id="currency" className="section container"><div className="split"><div className="card"><div className="eyebrow">LIVE CURRENCY</div><h2>Currency Converter</h2><p className="muted">Rates are requested live from the configured server-side provider. No rates are hardcoded.</p><div className="row"><input className="smallinput" value={currency.amount} onChange={e=>setCurrency({...currency,amount:e.target.value})}/><select className="select" value={currency.from} onChange={e=>setCurrency({...currency,from:e.target.value})}>{['USD','PKR','EUR','GBP','AED','SAR','QAR','KWD','BHD','OMR','TRY','MYR','CAD','AUD','JPY','CNY','INR'].map(x=><option key={x}>{x}</option>)}</select><select className="select" value={currency.to} onChange={e=>setCurrency({...currency,to:e.target.value})}>{['PKR','USD','EUR','GBP','AED','SAR','QAR','KWD','BHD','OMR','TRY','MYR','CAD','AUD','JPY','CNY','INR'].map(x=><option key={x}>{x}</option>)}</select></div><div className="tools"><button className="btn primary" onClick={getCurrency}><RefreshCw size={15}/> Get live rate</button></div><div className="result" style={{marginTop:15,fontSize:30}}>{currency.result||'—'}</div>{currency.updated&&<p className="muted" style={{fontSize:12}}>Last updated: {currency.updated}</p>}</div><div className="card"><h2>Bit vs Byte</h2><p className="muted">Internet speeds are commonly expressed in bits per second. File sizes are commonly expressed in bytes. 8 bits = 1 byte, so 200 Mbps = 25 MB/s.</p></div></div></section>
 <section id="calculators" className="section container"><div className="card"><div style={{display:'flex',alignItems:'center',gap:8}}><Calculator size={19}/><h2>Calculators</h2></div><div className="calcgrid"><div className="calc"><h3>BMI</h3><div className="row"><input className="smallinput" value={calc.kg} onChange={e=>setCalc({...calc,kg:e.target.value})} placeholder="kg"/><input className="smallinput" value={calc.m} onChange={e=>setCalc({...calc,m:e.target.value})} placeholder="m"/></div><p><b>{Number.isFinite(bmi)?bmi.toFixed(1):'—'}</b></p></div><div className="calc"><h3>Percentage</h3><div className="row"><input id="pv" className="smallinput" placeholder="Value"/><input id="pp" className="smallinput" placeholder="%"/></div><button className="btn" style={{marginTop:8}} onClick={()=>{const v=Number((document.getElementById('pv') as HTMLInputElement).value),p=Number((document.getElementById('pp') as HTMLInputElement).value);setMsg(`${p}% of ${v} = ${v*p/100}`)}}>Calculate</button></div><div className="calc"><h3>Discount</h3><div className="row"><input id="dp" className="smallinput" placeholder="Price"/><input id="dd" className="smallinput" placeholder="%"/></div><button className="btn" style={{marginTop:8}} onClick={()=>{const p=Number((document.getElementById('dp') as HTMLInputElement).value),d=Number((document.getElementById('dd') as HTMLInputElement).value);setMsg(`Final price = ${p*(1-d/100)}`)}}>Calculate</button></div><div className="calc"><h3>Tip</h3><div className="row"><input id="tb" className="smallinput" placeholder="Bill"/><input id="tt" className="smallinput" placeholder="%"/></div><button className="btn" style={{marginTop:8}} onClick={()=>{const b=Number((document.getElementById('tb') as HTMLInputElement).value),p=Number((document.getElementById('tt') as HTMLInputElement).value);setMsg(`Tip = ${b*p/100}; Total = ${b*(1+p/100)}`)}}>Calculate</button></div></div></div></section>
 <section id="history" className="section container"><div className="split"><div className="card"><h2>History</h2><div className="history">{history.length?history.map(x=><div className="historyrow" key={x.id}><span>{x.input} → {Number(x.result).toLocaleString()} {x.to}</span><button className="iconbtn" onClick={()=>{const n=history.filter(y=>y.id!==x.id);write('zeta-history',n);setHistory(n)}}><Trash2 size={14}/></button></div>):<p className="muted">No saved conversions.</p>}</div><button className="btn" style={{marginTop:12}} onClick={()=>{write('zeta-history',[]);setHistory([])}}>Clear history</button></div><div id="favorites" className="card"><h2>Favorites</h2><div className="history">{favorites.length?favorites.map(x=><div className="historyrow" key={x.id}><span>{x.input} → {x.result} {x.to}</span><button className="iconbtn" onClick={()=>{const n=favorites.filter(y=>y.id!==x.id);write('zeta-favorites',n);setFavorites(n)}}><Trash2 size={14}/></button></div>):<p className="muted">No favorites yet.</p>}</div></div></div></section>
 </main><footer className="footer"><div className="container">ZETA — Ultimate Universal Converter · Convert Anything. Instantly.</div></footer></div>
}
