'use client';
import { useMemo,useState } from 'react';
import { ArrowRightLeft, Copy, Search } from 'lucide-react';
import { convert } from '@/lib/converter/engine';
import { parseConversionRequest } from '@/lib/parser/natural';
export function ZetaDemo(){
 const [smart,setSmart]=useState('5 kg to pounds'); const [value,setValue]=useState(5); const [from,setFrom]=useState('kg'); const [to,setTo]=useState('lb');
 const parsed=useMemo(()=>parseConversionRequest(smart),[smart]); const result=useMemo(()=>{try{return convert(parsed?.value ?? value,parsed?.from ?? from,parsed?.to ?? to)}catch{return null}},[parsed,value,from,to]);
 const run=()=>{if(parsed){setValue(parsed.value);setFrom(parsed.from);setTo(parsed.to)}};
 return <main className="min-h-screen bg-background text-foreground"><header className="border-b"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><div className="text-xl font-bold tracking-tight">ZETA</div><nav className="hidden gap-6 text-sm md:flex"><span>Converter</span><span>Categories</span><span>Calculators</span><span>History</span><span>Favorites</span></nav></div></header><section className="mx-auto max-w-6xl px-6 py-20"><div className="max-w-3xl"><p className="mb-3 text-sm font-semibold uppercase tracking-widest text-muted-foreground">ZETA Universal Converter</p><h1 className="text-5xl font-semibold tracking-tight md:text-7xl">Convert Anything. Instantly.</h1><p className="mt-5 max-w-2xl text-lg text-muted-foreground">A deterministic, fast universal conversion platform for science, engineering, digital, financial and Pakistan-specific units.</p><div className="mt-10 flex gap-2 rounded-2xl border bg-card p-2 shadow-sm"><Search className="m-3 h-5 w-5 text-muted-foreground"/><input aria-label="Smart conversion request" value={smart} onChange={e=>setSmart(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} className="min-w-0 flex-1 bg-transparent outline-none" placeholder="Try: 5 kg to pounds"/><button onClick={run} className="rounded-xl bg-foreground px-5 py-3 text-background">Convert</button></div></div><div className="mt-12 grid gap-4 md:grid-cols-[1fr_auto_1fr]"><div className="rounded-3xl border bg-card p-6"><label className="text-sm text-muted-foreground">Amount</label><input type="number" value={value} onChange={e=>setValue(Number(e.target.value))} className="mt-2 w-full bg-transparent text-4xl font-semibold outline-none"/><input value={from} onChange={e=>setFrom(e.target.value)} className="mt-5 w-full rounded-xl border bg-transparent p-3" aria-label="Source unit"/></div><button aria-label="Swap units" className="self-center rounded-full border p-3"><ArrowRightLeft className="h-5 w-5"/></button><div className="rounded-3xl border bg-card p-6"><label className="text-sm text-muted-foreground">Result</label><div className="mt-2 text-4xl font-semibold">{result?result.value.toLocaleString(undefined,{maximumFractionDigits:10}):'—'}</div><input value={to} onChange={e=>setTo(e.target.value)} className="mt-5 w-full rounded-xl border bg-transparent p-3" aria-label="Target unit"/><div className="mt-5 flex items-center justify-between text-sm text-muted-foreground"><span>{result?.source.symbol} → {result?.target.symbol}</span><Copy className="h-4 w-4"/></div></div></div></section></main>
}
